"""Add is_admin field to users table

Revision ID: 4bd008239ee1
Revises: c4f738032ce9
Create Date: 2025-09-13 06:45:26.088687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd008239ee1'
down_revision: Union[str, Sequence[str], None] = 'c4f738032ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_status_published_at'), table_name='blog_posts')
    op.drop_constraint(op.f('uq_blog_posts_slug'), 'blog_posts', type_='unique')
    op.create_index(op.f('ix_blog_posts_id'), 'blog_posts', ['id'], unique=False)
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_status_created_at'), table_name='projects')
    op.drop_constraint(op.f('uq_projects_slug'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('uq_tags_name'), 'tags', type_='unique')
    op.drop_constraint(op.f('uq_tags_slug'), 'tags', type_='unique')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_admin')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_unique_constraint(op.f('uq_tags_slug'), 'tags', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_tags_name'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.create_unique_constraint(op.f('uq_projects_slug'), 'projects', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_projects_status_created_at'), 'projects', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.drop_index(op.f('ix_blog_posts_id'), table_name='blog_posts')
    op.create_unique_constraint(op.f('uq_blog_posts_slug'), 'blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_blog_posts_status_published_at'), 'blog_posts', ['status', 'published_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    # ### end Alembic commands ###
