"""Add featured column to projects table

Revision ID: 7a0b96046d45
Revises: da8b4ab0c5ae
Create Date: 2025-09-13 19:24:52.706274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0b96046d45'
down_revision: Union[str, Sequence[str], None] = 'da8b4ab0c5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_posts_slug_key'), 'blog_posts', type_='unique')
    op.drop_index(op.f('ix_blog_posts_published_at'), table_name='blog_posts')
    op.add_column('projects', sa.Column('featured', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('projects_slug_key'), 'projects', type_='unique')
    op.drop_constraint(op.f('tags_name_key'), 'tags', type_='unique')
    op.drop_constraint(op.f('tags_slug_key'), 'tags', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tags_slug_key'), 'tags', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tags_name_key'), 'tags', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('projects_slug_key'), 'projects', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('projects', 'featured')
    op.create_index(op.f('ix_blog_posts_published_at'), 'blog_posts', ['published_at'], unique=False)
    op.create_unique_constraint(op.f('blog_posts_slug_key'), 'blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
